// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Label label1;
    
    private Gtk.Entry xid;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Label label2;
    
    private Gtk.Entry password;
    
    private Gtk.HBox hbox3;
    
    private Gtk.CheckButton cbSSL;
    
    private Gtk.HBox hbox4;
    
    private Gtk.Label label3;
    
    private Gtk.Label lblVersion;
    
    private Gtk.Button button1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Login");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("Username");
        this.hbox1.Add(this.label1);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.xid = new Gtk.Entry();
        this.xid.CanFocus = true;
        this.xid.Name = "xid";
        this.xid.IsEditable = true;
        this.xid.InvisibleChar = '●';
        this.hbox1.Add(this.xid);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.xid]));
        w2.Position = 1;
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("Password");
        this.hbox2.Add(this.label2);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.label2]));
        w4.Position = 0;
        w4.Expand = false;
        w4.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.password = new Gtk.Entry();
        this.password.CanFocus = true;
        this.password.Name = "password";
        this.password.IsEditable = true;
        this.password.InvisibleChar = '●';
        this.hbox2.Add(this.password);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.password]));
        w5.Position = 1;
        this.vbox1.Add(this.hbox2);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.cbSSL = new Gtk.CheckButton();
        this.cbSSL.CanFocus = true;
        this.cbSSL.Name = "cbSSL";
        this.cbSSL.Label = Mono.Unix.Catalog.GetString("SSL");
        this.cbSSL.DrawIndicator = true;
        this.cbSSL.UseUnderline = true;
        this.hbox3.Add(this.cbSSL);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox3[this.cbSSL]));
        w7.Position = 0;
        // Container child hbox3.Gtk.Box+BoxChild
        this.hbox4 = new Gtk.HBox();
        this.hbox4.Name = "hbox4";
        this.hbox4.Spacing = 6;
        // Container child hbox4.Gtk.Box+BoxChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("XMPP Version:");
        this.hbox4.Add(this.label3);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox4[this.label3]));
        w8.Position = 0;
        w8.Expand = false;
        w8.Fill = false;
        // Container child hbox4.Gtk.Box+BoxChild
        this.lblVersion = new Gtk.Label();
        this.lblVersion.Name = "lblVersion";
        this.lblVersion.LabelProp = Mono.Unix.Catalog.GetString("label3");
        this.hbox4.Add(this.lblVersion);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox4[this.lblVersion]));
        w9.Position = 1;
        w9.Expand = false;
        w9.Fill = false;
        this.hbox3.Add(this.hbox4);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox3[this.hbox4]));
        w10.Position = 1;
        w10.Expand = false;
        w10.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Label = Mono.Unix.Catalog.GetString("Connect");
        this.hbox3.Add(this.button1);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox3[this.button1]));
        w11.Position = 2;
        w11.Expand = false;
        w11.Fill = false;
        this.vbox1.Add(this.hbox3);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
        w12.Position = 2;
        w12.Expand = false;
        w12.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 400;
        this.DefaultHeight = 124;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.button1.Clicked += new System.EventHandler(this.OnConnect);
    }
}
